apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-teams-bot
  namespace: cip-app
  labels:
    app: teams-bot
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: teams-bot
  template:
    metadata:
      labels:
        app: teams-bot
    spec:
      containers:
        - name: teams-bot
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            {{- range $key, $val := .Values.env }}
            - name: {{ $key }}
              value: {{ $val | quote }}
            {{- end }}
          {{- with .Values.envFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
