# TODO: Keycloak Helm values
# Chart: bitnami/keycloak
# Reference: https://github.com/bitnami/charts/tree/main/bitnami/keycloak
auth:
  adminUser: admin
  # adminPassword: set via K8s secret
production: true
proxy: edge
