# Chart: nats/nats
# helm repo add nats https://nats-io.github.io/k8s/helm/charts
# helm upgrade --install nats nats/nats -n cip-infra -f infra/helm/nats-values.yaml
config:
  jetstream:
    enabled: true
    fileStore:
      enabled: true
      pvc:
        enabled: true
        existingClaim: nats-data
container:
  merge:
    resources:
      requests:
        memory: 64Mi
        cpu: 25m
