# Chart: bitnami/postgresql
# helm repo add bitnami https://charts.bitnami.com/bitnami
# helm upgrade --install postgres bitnami/postgresql -n cip-infra -f infra/helm/postgres-values.yaml
global:
  postgresql:
    auth:
      username: cipuser
      existingSecret: postgres-credentials
      database: cip_hr
primary:
  persistence:
    enabled: true
    existingClaim: postgres-data
  resources:
    requests:
      memory: 128Mi
      cpu: 50m
