/**
 * Slice 47b followup: dump the LangGraph topology as a Mermaid diagram.
 *
 * Usage:
 *   pnpm --filter @cip/teams-bot tsx src/scripts/dump-graph-mermaid.ts \
 *     > ../../../slices/LANGGRAPH_ARCHITECTURE.md
 *
 * The graph STRUCTURE doesn't depend on the runtime BotAuthContext —
 * node factories close over ctx for execution but the node identities
 * + edges are static. So we pass a stub ctx, build the graph, and ask
 * LangGraph for its Mermaid representation. No DB / network needed.
 */

import { buildGraph } from '../langgraph/graph.js';
import type { BotAuthContext } from '../auth/resolve-context.js';

const stubCtx: BotAuthContext = {
  tenantId:    'graph-dump',
  userId:      'graph-dump',
  employeeId:  'graph-dump',
  permissions: {},
  roles:       [],
  bearerToken: '',
  tenantConfig: {
    tenantId:          'graph-dump',
    name:              'graph-dump',
    litellmVirtualKey: '',
    keycloakRealm:     'graph-dump',
    natsPrefix:        'graph-dump',
    langfuseTags:      {},
  },
};

const graph = buildGraph(stubCtx);
const mermaid = graph.getGraph().drawMermaid();

// Wrap in a markdown doc with header so the output is paste-ready into
// slices/LANGGRAPH_ARCHITECTURE.md.
const today = new Date().toISOString().slice(0, 10);
const out = `# LangGraph Runtime Architecture

> Auto-generated by \`packages/teams-bot/src/scripts/dump-graph-mermaid.ts\`.
> Regenerate when nodes or edges change. Do not hand-edit.
> Last generated: ${today}.

## Graph topology

\`\`\`mermaid
${mermaid.trim()}
\`\`\`

## Node summary

| Node | Purpose | LLM call? |
|---|---|---|
| \`ingest\` | Append HumanMessage; reset turn-scoped state. On confirm-resume, classify reply as affirm/cancel and synthesize an AIMessage with the saved tool call (skipping discover/triage/plan). | No |
| \`discover\` | Run \`discoverTools(ctx, latestUserText)\` — permission filter + Slice 44 vector retrieval. Hydrates \`candidateTools\`. Always re-runs (computed-not-persisted). | No |
| \`triage\` | Cheap classifier (\`cip-classifier\` → mistral-nemo). Outputs non-binding \`TriageSignals\`. Failure falls back to \`{needsTool: true, confidence: 0}\`. | Yes (\`bot.triage\`) |
| \`plan\` | Strong planner (\`cip-router-careful\` → mistral-small). Native function-calling over the candidate set. Reads recent messages + summary + tool-reference markdown. | Yes (\`bot.plan\`) |
| \`gateWrite\` | For each tool call, look up \`sideEffectLevel\`. Write/external + not explicitly authorized → stage \`pendingWriteCall\`, route to \`confirm\`. | No |
| \`confirm\` | Emit "About to: X. Reply yes/no." AIMessage. Graph ends; next user message resumes via \`ingest\`. | No |
| \`execute\` | Wraps \`executeTool()\`. Validates name against current \`candidateTools\` (rejects hallucinated names). Distills 1-line fact via \`distillFact()\`. | No (MCP call) |
| \`respond\` | Surface final AIMessage. Runner sends it to Teams + appends footer with \`turn=<id>\`. | No |

## Conditional edges

| From → branches | Routing logic | Tunable |
|---|---|---|
| \`ingest\` → \`execute\` / \`discover\` | If latest AIMessage has \`tool_calls\` (synthesized from \`pendingWriteCall\` resume) → \`execute\`. Else → \`discover\`. | — |
| \`triage\` → \`respond\` / \`plan\` | If \`triage.needsClarification\` AND \`triage.confidence ≥ lg.triage_clarify_threshold\` AND \`triage.clarificationQuestion\` set → \`respond\`. Else → \`plan\`. | \`lg.triage_clarify_threshold\` |
| \`gateWrite\` → \`confirm\` / \`execute\` / \`respond\` | \`pendingWriteCall\` set → \`confirm\`. AIMessage has \`tool_calls\` → \`execute\`. Else → \`respond\`. | \`lg.authorized_write_verbs\` |
| \`execute\` → \`plan\` / \`respond\` | \`stepCount ≥ lg.max_steps\` → \`respond\`. Else → \`plan\` (loop). | \`lg.max_steps\` |

## State persistence

In-process \`MemorySaver\` keyed by Teams \`thread_id\`. Survives node-to-node + successive turns within a pod's lifetime. Lost on restart, lost across replicas. **Slice 46** swaps to \`PostgresSaver\`.

\`candidateTools\` is computed-not-persisted — re-derived from the live MCP catalog on every turn entry AND on resume from a confirm interrupt. This guarantees a confirm→resume cycle uses the user's CURRENT permitted tool set.

## Trace correlation

Each turn generates an 8-char hex \`turnId\` at runner entry. It's:
- Surfaced in the Teams response footer as \`turn=\\\`<id>\\\`\`
- Included in the \`[turn]\` log line as \`turn=<id>\`
- Passed as Langfuse \`trace_id\` metadata on every LLM call (Slice 48 wires this into the Langfuse trace tree)

To debug a turn: copy the \`turn=<id>\` from the user's footer, grep pod logs for \`turn=<id>\`, and (Slice 48) jump to the Langfuse trace.
`;

console.log(out);
